-- Создайте таблицу logs типа Archive.
-- Пусть при каждом создании записи в таблицах users, catalogs и products
-- в таблицу logs помещается время и дата создания записи, название таблицы, идентификатор первичного ключа и содержимое поля name.

DROP TABLE IF EXISTS LOGS;
CREATE TABLE LOGS
  (
    CREATED_AT DATETIME NOT NULL,
    TABLE_NAME VARCHAR(50) NOT NULL,
    PRIMARY_KEY_ID INT NOT NULL,
    NAME_CONTENTS VARCHAR(100)
  )
ENGINE = ARCHIVE;

DROP TRIGGER IF EXISTS USER_LOGS;
DELIMITER //

CREATE TRIGGER USER_LOGS AFTER INSERT ON USERS
FOR EACH ROW
BEGIN
INSERT INTO LOGS (CREATED_AT, TABLE_NAME, PRIMARY_KEY_ID, NAME_CONTENTS)
VALUES (NOW(), 'USERS', NEW.ID, NEW.NAME);

END//
DELIMITER ;

DROP TRIGGER IF EXISTS CATALOGS_LOGS;
DELIMITER //

CREATE TRIGGER CATALOGS_LOGS AFTER INSERT ON CATALOGS
FOR EACH ROW
BEGIN
INSERT INTO LOGS (CREATED_AT, TABLE_NAME, PRIMARY_KEY_ID, NAME_CONTENTS)
VALUES (NOW(), 'CATALOGS', NEW.ID, NEW.NAME);

END//
DELIMITER ;

DROP TRIGGER IF EXISTS PRODUCTS_LOGS;
DELIMITER //

CREATE TRIGGER PRODUCTS_LOGS AFTER INSERT ON PRODUCTS
FOR EACH ROW
BEGIN
INSERT INTO LOGS (CREATED_AT, TABLE_NAME, PRIMARY_KEY_ID, NAME_CONTENTS)
VALUES (NOW(), 'PRODUCTS', NEW.ID, NEW.NAME);

END//
DELIMITER ;

#########################################################

SELECT * FROM USERS;

INSERT INTO USERS
(NAME, BIRTHDAY_AT)
VALUES
('Smith', '1963/04/12'),
('Neo', '1923/09/11'),
('Trinity', '1993/10/02');

SELECT * FROM USERS;
SELECT * FROM LOGS;

SELECT * FROM CATALOGS;

INSERT INTO CATALOGS
(NAME)
VALUES
('Строительные материалы'),
('Сад и огород'),
('Автозапчасти');

SELECT * FROM CATALOGS;
SELECT * FROM LOGS;

SELECT * FROM PRODUCTS;

INSERT INTO PRODUCTS
(NAME, DESCRIPTION, PRICE, CATALOG_ID)
VALUES
('Цемент','Мешок 50 кг','10','12'),
('Вилы','Для копания','30','13'),
('Шелковая тряпочка','Для протирания пыли с Rolls-Royce','100000','14');

SELECT * FROM PRODUCTS;
SELECT * FROM LOGS;
